name: Run RIFT tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y ninja-build

      - name: Configure CMake project
        run: |
          mkdir build
          cd build
          cmake .. -DRIFT_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ./rift_test
          if [ $? -ne 0 ]; then
              exit 1
          fi